project_id = "caqjobwfcuwvxojengky"

[functions.invite-app-user]
verify_jwt = true

[functions.update-app-user]
verify_jwt = true

[functions.delete-app-user]
verify_jwt = true

[functions.delete-order]
verify_jwt = false

[functions.delete-customer]
verify_jwt = false

[functions.resend-invite]
verify_jwt = true

[functions.send-order-email]
verify_jwt = false

[functions.save-email-settings]
verify_jwt = true

[functions.test-email-smtp]
verify_jwt = true